### ISSUE TITLE
Current Activity is null

### ISSUE THREAD

**Issue by djordje200179** [TobiasBuchholz/Plugin.Firebase#67] opened 2022-09-13 08:46 UTC
When I run the app on Android the exception "_Current Activity is null, ensure that the MainApplication.cs file is setting the CurrentActivity in your source code so Firebase Analytics can use it._" is raised, and I can't figure out am I doing something wrong.

I have initialized the plugin as stated in documentation.
![image](https://user-images.githubusercontent.com/17686905/189850997-0b7be437-8bdb-4a87-8b61-3f7a65cc19d5.png)

**Comment by vhugogarcia** [comment] 2022-10-26 20:30
I am facing the same issue you are @djordje200179 . Did you find a workaround for it?

**Comment by djordje200179** [comment] 2022-10-26 20:41
@vhugogarcia Nope :/
I have tried a lot of things, but that didnt solve the problem. And unfortunately owner of the repo didn't say anything about the issue. So we are stuck until someone figures out what we are doing wrongly.

**Comment by vhugogarcia** [comment] 2022-10-26 20:47
I tried to implement Analytics on my own following the same logic from this plugin without success. After debugging the issue the activity is not null, somehow the Initialize static method is not assigning correctly the object for instance it is null.

https://github.com/TobiasBuchholz/Plugin.Firebase/blob/c2d5c5f8bfb598c4cb8439a0ac2f6db6cee92c69/src/Android/Analytics/FirebaseAnalyticsImplementation.cs#L16

The code line above in the link is the one that is not being triggered somehow, I'm not sure why. I'm still investigating...

**Comment by TobiasBuchholz** [comment] 2022-10-27 07:54
Hi, sorry for not giving any feedback yet, I was hoping the problem might have solved itself. If you provide me with an example project with this issue I can take a look and try to help.

**Comment by tranb3r** [comment] 2023-01-25 20:40
Duplicate of #67

**Comment by tranb3r** [comment] 2023-01-25 20:53
I'm also having this exception sometimes, in two different situations:
- app resumes after a period of inactivty (activity destroyed)
- app launched after the process has been started by a background worker

I haven't been able to debug the first situation.

However the second situation is easy to reproduce, and here is what happens:
- the background worker starts, of course there is no activity so Platform.CurrentActivity is null (which is legit)
- when a call to CrossFirebaseAuth.Current is done (by the worker), the constructor of FirebaseAuthImplementation is called ; in this constructor, an exception is thrown when getting Platform.CurrentActivity on GoogleAuth init.
- as CrossFirebaseAuth.Current is using a Lazy valueFactory, any attempt to initialize again FirebaseAuthImplementation is failing, even if it's done later in the app when an Activity does exist.

So, one problem is that an exception is thrown in the constructor of a class which is called by a Lazy valueFactory.
This problem can be avoided if the Platform.CurrentActivity is not retrieved in the constructor. Which is exactly what I've done in PR #122

**Comment by TobiasBuchholz** [comment] 2023-01-30 20:41
PR #122 is now merged into the main branch and released with version 1.3.0.

**Comment by gianox** [comment] 2023-05-11 11:38
I can confirm that "The current Activity can not be detected." happens as long as the POST_NOTIFICATIONS permission has not yet been accepted by the user. That would be fine if it didn't crash the app. If using the current workaround: 

ActivityCompat.RequestPermissions(this, new[] { Android.Manifest.Permission.PostNotifications }, 0);

You still get a crash - but only on the first time starting where you have to accept the permission.

**Closed** 2023-11-16 09:29 UTC
