### ISSUE TITLE
.NET MAUI and AOT compilation

### ISSUE THREAD

**Issue by kalpasrl** [TobiasBuchholz/Plugin.Firebase#258] opened 2024-02-05 11:37 UTC
In our project if I use the release configuration in Android, the compilation is done in AOT and in this case push notifications are not received.
Is there a problem with trimming assemblies?

Plugin.Firebase.CloudMessaging version 2.0.4

Thank you

**Comment by kalpasrl** [comment] 2024-02-05 17:01
My csproj is:

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-android|AnyCPU'">
		<AndroidPackageFormats>apk;aab</AndroidPackageFormats>
		<DefineConstants>$(DefineConstants);RELEASE;</DefineConstants>
		<RunAOTCompilation>True</RunAOTCompilation>
		<Optimize>True</Optimize>
		<PublishTrimmed>True</PublishTrimmed>
	</PropertyGroup>

What is the way to exclude FirebaseMessagingService from trimming?

**Comment by tranb3r** [comment] 2024-02-05 17:10
Ok, so it's indeed trimming (PublishTrimmed), not AOT (RunAOTCompilation), which is causing trouble.

I've described the same issue here: https://github.com/TobiasBuchholz/Plugin.Firebase/issues/144#issuecomment-1716038986

Here is a possible workaround for it: add the following attribute to your app initialization code:
`[DynamicDependency(DynamicallyAccessedMemberTypes.All, "Plugin.Firebase.CloudMessaging.Platforms.Android.MyFirebaseMessagingService", "Plugin.Firebase.CloudMessaging")]`

**Comment by kalpasrl** [comment] 2024-02-06 14:35
Thank you @tranb3r 

RunAOTCompilation cannot be used without PublishTrimmed=true

**Comment by Quaybe** [comment] 2024-02-27 20:08
> Ok, so it's indeed trimming (PublishTrimmed), not AOT (RunAOTCompilation), which is causing trouble.
> 
> I've described the same issue here: [#144 (comment)](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/144#issuecomment-1716038986)
> 
> The easiest workaround is to skip trimming for the Plugin.Firebase.CloudMessaging assembly: `<TrimmerRootAssembly Include="Plugin.Firebase.CloudMessaging" RootMode="All" />`

This workaround no longer works for me. I'm not sure why. I believe I had trimming enabled with the TrimmerRootAssembly excluding Plugin.Firebase in my csproj file and it had worked in the past, but not now.

I've tried RootMode="Library" as well with no luck. I am forced to disable trimming completely until this issue is fixed with Firebase.

**Comment by tranb3r** [comment] 2024-02-28 07:34
> it had working in the past, but not now

What did you change?
My recommandation would be to inspect the dll after build, in order to check the result of the trimmer. This would allow you to know wether your csproj is properly configured or not.

**Comment by Quaybe** [comment] 2024-03-01 16:17
> > it had working in the past, but not now
> 
> What did you change? My recommandation would be to inspect the dll after build, in order to check the result of the trimmer. This would allow you to know whether your csproj is properly configured or not.

I updated Visual Studio. 

I tried all sorts of recommended variations to get the trimming to leave Plugin.Firebase or Plugin.Firebase.Messaging alone, but it no longer works. 

My issue is, when trimming is enabled, I do get a notification from Firebase, but it's as if my app is in the background even though I have it in the foreground. I have logic built in to ignore the notifications from OnMessageReceieved if my app is in the foreground and certain pages are focused. With trimming enabled, OnMessageReceived is ignored completely and I get the notification as if my app isn't open at all. Trimming off, works fine, but only if I turn it off completely.

**Comment by kalpasrl** [comment] 2024-03-20 16:41
Unfortunately, even with the latest fixes made on .NET Android, the problem persists.

**Comment by Quaybe** [comment] 2024-04-02 14:49
> I’ve gotten it to work in release by using these settings in the csproj:
> 
> `<RunAOTCompilation>False</RunAOTCompilation> <PublishTrimmed>false</PublishTrimmed>`

Isn't that just turning off AOT Compilation and Trimming for everything?

**Comment by Quaybe** [comment] 2024-04-02 15:10
Yeah, I'm in the exact same boat. Just wanted to make sure I understood correctly.

**Comment by angelru** [comment] 2024-04-09 07:16
Push notifications work for me
https://github.com/angelru/ValdemoroEn1/blob/dev/src/ValdemoroEn1/ValdemoroEn1.csproj
https://github.com/angelru/ValdemoroEn1/blob/dev/src/ValdemoroEn1/Platforms/Android/proguard.cfg

**Comment by kalpasrl** [comment] 2024-05-10 13:53
@angelru 
I tried your suggestions but it doesn't work for me

**Comment by kalpasrl** [comment] 2024-05-13 07:58
@jkommeren 
I confirm that notification with **data** type message don't work. 
I receiving **regular** notification because are managed by operating sysstem and not by the app.

**Comment by tranb3r** [comment] 2024-05-13 08:18
@jkommeren @kalpasrl 
I have all scenarios working in my app.
So there must be something wrong in your app.
I insist you should check that you still have `Plugin.Firebase.CloudMessaging.Platforms.Android.MyFirebaseMessagingService` in your assembly after trimming. The notification won't work if the trimmer gets rid of this android service (which is happening by default).

**Comment by tranb3r** [comment] 2024-05-13 09:10
I think there are two ways to preserve this service (both are working):
- add `<TrimmerRootAssembly Include="Plugin.Firebase.CloudMessaging" RootMode="All" />` to your csproj.
- add `[DynamicDependency(DynamicallyAccessedMemberTypes.All, "Plugin.Firebase.CloudMessaging.Platforms.Android.MyFirebaseMessagingService", "Plugin.Firebase.CloudMessaging")]` somewhere in your code.

**Comment by jkommeren** [comment] 2024-05-13 18:19
Thanks man, it looks like I'm getting there! 

The TrimmedRootAssembly suggestion entry did not seem to do anything (maybe because trim was set to full by default? I just put it into an item group in csproj like this (I had done it previously for another dependency that failed because it was trimmed)
`   
<ItemGroup>
     <TrimmerRootAssembly Include="Plugin.Firebase.CloudMessaging" RootMode="All" />
</ItemGroup>
`

... But adding the DynamicDependency
`    [DynamicDependency(DynamicallyAccessedMemberTypes.All, "Plugin.Firebase.CloudMessaging.Platforms.Android.MyFirebaseMessagingService", "Plugin.Firebase.CloudMessaging")]
`
Like you suggested to the top of my AppShell constructor did work with your library! :) Data messages are being received. I can't believe it. Thanks so much!

Now I'm wondering how I can get this to work with my own FirebaseMessagingService implementation. But that's probably too much to ask of you :D

**Comment by tranb3r** [comment] 2024-05-13 18:52
> The TrimmedRootAssembly suggestion entry did not seem to do anything (maybe because trim was set to full by default? I just put it into an item group in csproj like this (I had done it previously for another dependency that failed because it was trimmed) ` <ItemGroup> <TrimmerRootAssembly Include="Plugin.Firebase.CloudMessaging" RootMode="All" /> </ItemGroup>`

It should definitely work with full trimming mode. And actually, it's not needed if you do not trim in full mode.
Most probably you did not clean properly before rebuild. If you want to try again, make sure you close VS and remove bin & obj folders, before rebuilding your app.

> ... But adding the DynamicDependency ` [DynamicDependency(DynamicallyAccessedMemberTypes.All, "Plugin.Firebase.CloudMessaging.Platforms.Android.MyFirebaseMessagingService", "Plugin.Firebase.CloudMessaging")]` Like you suggested to the top of my AppShell constructor did work with your library! :) Data messages are being received. I can't believe it. Thanks so much!

You're welcome.
Just be careful with this fix. It's actually more a workaround. It could break if the code of Plugin.Firebase changes. The idea is to make sure the service is preserved. But this should actually be part of the plugin initialization.

**Comment by jkommeren** [comment] 2024-05-15 16:31
> @jkommeren 
> I'm happy for you, unfortunately it still doesn't work for me.
> Upon receiving a notification, logcat writes this:
> ```
> 05-15 17:27:45.340 21162 23707 I NotificationManager: com.company.app: notify(1337, null, Notification(channel=null shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)) as user
> 05-15 17:27:45.346  1376  5727 E NotificationService: No Channel found for pkg=com.company.app, channelId=null, id=1337, tag=null, opPkg=com.company.app, callingUid=10514, userId=0, incomingUserId=0, notificationUid=10514, notification=Notification(channel=null shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
> ```

Here's the obvious question: are you creating your notification channel? I set up mine in the MainApplication.cs's OnCreate . (Which is also executed at startup of Android)

After that you need to inform the plugin what the channel id is that you just created.

Check https://github.com/coop-tim/maui-sample/blob/main/MauiSample/Platforms/Android/MainActivity.cs 

For an example.

**Comment by kalpasrl** [comment] 2024-05-16 13:19
I found the problem, the registration to the channel was done in the wrong place in the app.
Thank you @jkommeren

**Comment by jkommeren** [comment] 2024-05-16 13:47
> I found the problem, the registration to the channel was done in the wrong place in the app.
> Thank you @jkommeren 

You're welcome. Thanks for posting back!

**Closed** 2024-06-05 16:10 UTC

**Comment by Xopabyteh** [comment] 2024-10-30 12:58
I Have come across the same issue. When i recieve a notification with only **data** and no body, there is unexpected behaviour:
In debug mode, without trimming and with no AOT, the app spins up in the `OnMessageReceived` is called,
but in release mode with trimming and AOT, it is not called and the notification displays as an empty notification without a body, title and with the gray circle.

I've tried doing what was discussed here, but to no help.

FirebaseMessaagingService:
```cs

[Service(Exported = true)]
[IntentFilter(new[] { "com.google.firebase.MESSAGING_EVENT" })]
// ReSharper disable once UnusedMember.Global
public class AppFirebaseMessagingService : MyFirebaseMessagingService
{
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(MyFirebaseMessagingService))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(AppFirebaseMessagingService))]
    public AppFirebaseMessagingService()
        : base()
    {
    }

    public override void OnNewToken(string token)
    {
        base.OnNewToken(token);
        
        // Prints in debug, not in release
        Console.WriteLine($"MaGyRakovina.FirebaseMessagingService Reg token: {token}");
    }

    public override async void OnMessageReceived(RemoteMessage message)
    {
        base.OnMessageReceived(message);
        
        // Prints in debug, not in release
        Console.WriteLine("MaGy FCM Message received");
        
        // Do stuff...
    }
}
```
csproj:
```xml
    
    <!--Trimming  &AOT-->
    <ItemGroup Condition="$(TargetFramework.Contains('-android'))">
        <TrimmerRootDescriptor Include="Platforms\Android\ILLink.Descriptors.xml" />
       
        <ProguardConfiguration Include="Platforms\Android\proguard.cfg" />
    </ItemGroup>
    <PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
        <AndroidUseAapt2>True</AndroidUseAapt2>
        <AndroidLinkTool>r8</AndroidLinkTool>
    </PropertyGroup>
```

i have the same proguard file as mentioned [https://github.com/TobiasBuchholz/Plugin.Firebase/issues/258#issuecomment-2044301020](here)

ILLink.Descriptors.xml
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<linker>
  <!--
  Remove from linking, camera zoom doesn't work in release mode: 
  https://github.com/CommunityToolkit/Maui/issues/2109
  -->
  <assembly fullname="Xamarin.AndroidX.Camera.Core" />
  
  <assembly fullname="Plugin.Firebase.CloudMessaging"/>
</linker>
```
