### ISSUE TITLE
Bitcode is deprecated in iOS. facing issue while implementing this plugin.

### ISSUE THREAD

**Issue by faheem-riaz** [TobiasBuchholz/Plugin.Firebase#146] opened 2023-03-09 01:56 UTC
I am using the latest version of plugin.firebase 1.3.0. Apple has deprecated the bitcode. So I am able to created a build but cannot be able to publish the app. I am getting errors that are shown in image below.
Firebase packages are upgraded I believe. Please update your package so that we can release our app on iOS 16 and above.
![Screenshot 2023-03-09 at 6 58 36 AM](https://user-images.githubusercontent.com/42313806/223896113-f5c4885a-a77c-45e1-bb80-097f1dd62df2.png)

**Comment by hattmann** [comment] 2023-03-09 09:56
Same issue here!

Using plugin.firebase.temp fixes this issues for me.

![image](https://user-images.githubusercontent.com/4472613/223986005-505cd818-b0c8-48e5-8c6b-ee6b91c7fba6.png)

Are there plans for a new release without bitcode in the near future?

**Comment by hattmann** [comment] 2023-03-09 11:45
Yes, give it a try

Stefan Habacher ***@***.***> schrieb am Do., 9. März 2023,
12:21:

**Comment by stoff99** [comment] 2023-03-09 11:50
@hattmann i will, but i don't know what you mean with plugin.firebase.temp. Can you explain what you did?

**Comment by faheem-riaz** [comment] 2023-03-09 11:52
@hattmann  Yeah give some idea how to use plugin.firebase.temp

**Comment by hattmann** [comment] 2023-03-09 11:59
Here ist the nuget and the information:

https://www.nuget.org/packages/Plugin.Firebase.Tmp

For me just adding this nuget and after that removing the original nuget helped. I just need the Firebase Push function without the Facebook and authorisation libs.

**Comment by stoff99** [comment] 2023-03-09 12:50
Hi @hattmann,
thx for that. I can confirm its working with .net7 maui ios aswell. For me its the same, i only need the push notification service.

But still, is this the final solution to avoid this problem @TobiasBuchholz ?

**Comment by faheem-riaz** [comment] 2023-03-11 03:21
@hattmann  Plugin.Firebase.temp does not contain crashlytics. Any suggestions what should I use now? @TobiasBuchholz @stoff99

**Comment by mw6201** [comment] 2023-03-11 08:33
When adding Plugin.FireBase.Tmp package instead of Plugin.FireBase the Plugin.FireBase.Auth Namespace is missing. Any suggestions?

**Comment by hattmann** [comment] 2023-03-11 10:52
I think you have to wait until the author provides a new release that adresses this issue.

**Comment by TobiasBuchholz** [comment] 2023-03-12 15:01
Hi! Please take a look at https://github.com/TobiasBuchholz/Plugin.Firebase/issues/95#issuecomment-1347248607 to understand the problem with bitcode on iOS. I'm currently working on a version of the firebase plugin, that splits all features into single nuget packages as suggested by vhugogarcia in https://github.com/TobiasBuchholz/Plugin.Firebase/issues/115#issuecomment-1405163230, so you won't have to include auth or facebook related packages which are causing the bitcode issue. Until then you'll need to follow nebular2s advice: https://github.com/TobiasBuchholz/Plugin.Firebase/issues/95#issuecomment-1348602401

**Comment by TobiasBuchholz** [comment] 2023-03-12 15:02
I'll close this issue since it's a duplication of https://github.com/TobiasBuchholz/Plugin.Firebase/issues/95.

**Closed by TobiasBuchholz** 2023-03-12 15:02 UTC

**Comment by tranb3r** [comment] 2023-03-12 16:47
> Hi! Please take a look at [#95 (comment)](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/95#issuecomment-1347248607) to understand the problem with bitcode on iOS. I'm currently working on a version of the firebase plugin, that splits all features into single nuget packages as suggested by vhugogarcia in [#115 (comment)](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/115#issuecomment-1405163230), so you won't have to include auth or facebook related packages which are causing the bitcode issue. Until then you'll need to follow nebular2s advice: [#95 (comment)](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/95#issuecomment-1348602401)

@TobiasBuchholz
Is the split of all features really necessary?
As I said [here](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/115#issuecomment-1452498136) the trimmer is taking good care of removing the code that is not used.
Except for the Facebook SDK ; and maybe a few things that should be tested again as I mentioned [here](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/144#issue-1608344577).
What do you think?

**Comment by hattmann** [comment] 2023-03-12 17:58
@tranb3r TrimMode=Full is the default in. NET7, the bitcode is include despite it. Please see the ITunes Connect Failures I posted before

**Comment by tranb3r** [comment] 2023-03-13 07:43
> @tranb3r TrimMode=Full is the default in. NET7, the bitcode is include despite it. Please see the ITunes Connect Failures I posted before

TrimMode=Full is the default in net7, but not for maui. You have to opt-in to full mode. At least for android, but I guess it's the same for iOS.
https://learn.microsoft.com/en-us/dotnet/maui/migration/android-projects?view=net-maui-7.0#linker

Also, the bitcode comes from the Facebook SDK. This one is not completely trimmed (even in full mode). This is why it was suggested to remove this SDK from this plugin.

**Comment by TobiasBuchholz** [comment] 2023-03-13 19:10
> @TobiasBuchholz
Is the split of all features really necessary?
As I said https://github.com/TobiasBuchholz/Plugin.Firebase/issues/115#issuecomment-1452498136 the trimmer is taking good care of removing the code that is not used.
Except for the Facebook SDK ; and maybe a few things that should be tested again as I mentioned https://github.com/TobiasBuchholz/Plugin.Firebase/issues/144#issue-1608344577.
What do you think?

I'm almost finished splitting up all the features into single nuget packages and it looks good so far. There will be a package that bundles all the separated nuget packages into a single one so the plugin can be used like before. On the other hand people who don't trust the trimmer or who are encountering something like build issues not related to the feature they would actually like to use can just install the separated nuget package and might get better results.
