### ISSUE TITLE
Windows 11 MAUI App could not find part of the path error

### ISSUE THREAD

**Issue by SteveSitekitcare** [TobiasBuchholz/Plugin.Firebase#199] opened 2023-09-14 11:08 UTC
Hi all,

I have a MAUI app that uses dotnet 7. I seem to be having the problem mentioned in [HERE](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/65)

The problem is I've tried the fixes to enable long filename support in windows 11 but none seem to work. It may be related to [THIS](https://answers.microsoft.com/en-us/windows/forum/all/long-file-path-issues-in-windows-11-pro-with/0c440721-e35a-4b58-9f5a-645656768f9d)

The error occurs when trying to install the Plugin.Firebase nuget package

`Could not find a part of the path 'c:\nuget\xamarin.firebase.ios.cloudfirestore\8.10.0.3\lib\xamarinios10\Firebase.CloudFirestore.resources\grpcpp.xcframework\ios-arm64_x86_64-simulator\grpcpp.framework\PrivateHeaders\src\core\ext\filters\client_channel\lb_policy\grpclb\client_load_reporting_filter.h`

I tried the dotnet command and it didnt work either (I had enabled long filename support)

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/138577988/496322e5-d0cd-4100-9d8d-289aaabc505b)

Does anyone have any ideas?

**Comment by SteveSitekitcare** [comment] 2023-09-15 10:23
So I just tried it on a windows 10 machine and its fine, so this looks to be a windows 11 issue

**Comment by Kirk-iOS** [comment] 2023-10-11 07:38
I too am having this issue on Windows 11. It appears there is an issue with long filenames on windows 11.  @SteveSitekitcare did you find a solution to this or downgrade to Windows 10?

**Comment by SteveSitekitcare** [comment] 2023-10-11 08:47
> I too am having this issue on Windows 11. It appears there is an issue with long filenames on windows 11. @SteveSitekitcare did you find a solution to this or downgrade to Windows 10?

I had to use windows 10. I tried the environment variable to set the nuget path to c:\nuget and that still didnt give me enought space. The fixes that work for windows 10 (policy/registry) dont work on windows 11.

**Comment by AdamEssenmacher** [comment] 2023-10-19 22:02
Try clearing your local nuget cache and running a `nuget restore` from command line (not from Visual Studio).

**Comment by SteveSitekitcare** [comment] 2023-10-20 11:02
> Try clearing your local nuget cache and running a `nuget restore` from command line (not from Visual Studio).

Setting the nuget path to c:\nuget in the Environement variables reset the nuget c cache as it had to pull all the packages again

**Comment by ispysoftware** [comment] 2023-11-06 09:01
yeah something here is thoroughly broken - there's either a missing file in the nuget package or some limit on the path length on windows 11 is preventing it from being installed. Removing path length limits in windows doesn't fix it.

**Comment by AdamEssenmacher** [comment] 2023-11-06 16:36
I don't think there's much this plugin's developers can do. The problem is that the Xamarin.Firebase.iOS Nuget packages are getting packed with long file paths, so the issue would probably be better reported over at https://github.com/xamarin/GoogleApisForiOSComponents

Even then, I don't know if there's anything the Xamarin devs will be able to do about it either. With iOS moving to xcframeworks to bundle multiplatform binaries, the resulting file paths are going to be longer than what Visual Studio is able to support.

I have been able to restore these packages on Windows 10 just fine **on the command line** and **after clearing the local nuget cache**. These packages will simply not work if they're restored via the Visual Studio IDE, which does not support long file paths and--by Microsoft's own statements--probably won't for the next 5-10 years.

**Closed** 2023-11-16 09:56 UTC

**Comment by ispysoftware** [comment] 2023-11-17 01:17
@TobiasBuchholz I wouldn't call this issue closed - let alone "completed" - it's probably better to leave it open until it's resolved.
We had to completely re-write our ios project in swift because this was a complete show stopper.

**Comment by AdamEssenmacher** [comment] 2023-11-17 06:18
>  it's probably better to leave it open until it's resolved.

To what end? The solution is well outside the scope of this project, and there's a known workaround.

**Comment by SteveSitekitcare** [comment] 2023-11-17 15:16
Just wondering if anyone has tried this in Jetbrains Rider on windows?
