### ISSUE TITLE
Type is defined multiple times build issue 

### ISSUE THREAD

**Issue by Noobicle** [TobiasBuchholz/Plugin.Firebase#172] opened 2023-06-12 15:12 UTC
Hello,

I've been using the crashalytics plugin with great sucess(Thank you!). On installing the analytics plugin I am getting the following error;
```

Error in obj\Debug\net7.0-android33.0\lp\233\jl\classes.jar:com/google/android/gms/internal/measurement/zzef.class:
Type com.google.android.gms.internal.measurement.zzef is defined multiple times: obj\Debug\net7.0-android33.0\lp\233\jl\classes.jar:com/google/android/gms/internal/measurement/zzef.class, obj\Debug\net7.0-android33.0\lp\261\jl\classes.jar:com/google/android/gms/internal/measurement/zzef.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\net7.0-android33.0\lp\233\jl\classes.jar
com/google/android/gms/internal/measurement/zzef.class
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
	at com.android.tools.r8.D8.main(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj\Debug\net7.0-android33.0\lp\233\jl\classes.jar:com/google/android/gms/internal/measurement/zzef.class
	at Version.fakeStackEntry(Version_3.3.75.java:0)
<Removed>

Directory 'obj\Debug\net7.0-android33.0\lp\233' is from 'play-services-measurement-sdk-api.aar'.	
```

I've found the conflict appears to be between the MauiMTAdmob(https://github.com/marcojak/MauiMTAdmob) plugin and your analytics plugin. 

I've tried googling to no avail do you have any recommendation on how I can fix this?

I'm quite new to MAUI/Xamarin so please forgive me if it's a really obvious solution.

**Comment by Noobicle** [comment] 2023-06-14 12:21
Sadly not. It all progresses correctly no warnings given.

**Comment by TobiasBuchholz** [comment] 2023-06-14 21:00
Sorry, for now I didn't find an solution for this issue but I was able to reproduce it with the sample project of the plugin, so when I've got time I'll take a look into it again. Until then please let us know in case you find a solution by yourself.

**Comment by Noobicle** [comment] 2023-06-14 21:21
Thank you for responding. It makes me happy to know it's reproducible!

I will update if I find the solution. 

Sorry for the hassle and thank you for the great work.

**Comment by jeff-eats-pubsubs** [comment] 2023-07-18 21:13
Delete bin and obj folders from root and build again

**Comment by Noobicle** [comment] 2023-07-18 21:19
> Delete bin and obj folders from root and build again

Already tried the basics but thank you :).

**Comment by jeff-eats-pubsubs** [comment] 2023-07-18 21:20
I am a noob lol. Was worth mentioning

**Comment by Noobicle** [comment] 2023-07-18 21:20
Aren't we all :)

**Comment by jeff-eats-pubsubs** [comment] 2023-07-18 21:22
MAUI is a beast

**Comment by TobiasBuchholz** [comment] 2023-11-16 09:50
Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide the more information so that I can look into it further. Thank you!

**Comment by cagriy** [comment] 2023-11-19 15:31
I am having the same issue @TobiasBuchholz , albeit slightly different error message:

```
0>: Error JAVA0000 java: Error in /Users/cagri/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.1/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class:
Type androidx.collection.ArrayMapKt is defined multiple times: /Users/cagri/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.1/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, /Users/cagri/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.5/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/cagri/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.1/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-jvm.jar
androidx/collection/ArrayMapKt.class
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
```

**Comment by Noobicle** [comment] 2023-11-19 15:34
> Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide the more information so that I can look into it further. Thank you!

Hey as far as I'm aware it's still an issue.

I was just patiently waiting for you to fix it. Didn't want to bug you.

**Comment by cagriy** [comment] 2023-11-19 15:35
Can you reopen this issue @Noobicle ? As per Tobias's message above ?

**Comment by Noobicle** [comment] 2023-11-19 15:40
> Can you reopen this issue @Noobicle ? As per Tobias's message above ?

I'm not sure I can reopen it. At least I cannot find a option to do it anywhere.

**Comment by TobiasBuchholz** [comment] 2023-11-19 15:44
> I am having the same issue @TobiasBuchholz , albeit slightly different error message:
> 
> ```
> 0>: Error JAVA0000 java: Error in /Users/cagri/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.1/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class:
> Type androidx.collection.ArrayMapKt is defined multiple times: /Users/cagri/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.1/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, /Users/cagri/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.5/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class
> Compilation failed
> java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/cagri/.nuget/packages/xamarin.androidx.collection.jvm/1.3.0.1/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-jvm.jar
> androidx/collection/ArrayMapKt.class
> 	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
> ```

If you are using the newest version of the plugin this issue should be fixed by replacing

```xml
<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
  <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk7" Version="1.7.10" ExcludeAssets="build;buildTransitive" />
  <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk8" Version="1.7.10" ExcludeAssets="build;buildTransitive" />
</ItemGroup>
```

with 

```xml
<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
    <PackageReference Include="Xamarin.AndroidX.Core" Version="1.12.0.2" />
    <PackageReference Include="Xamarin.AndroidX.Collection" Version="1.3.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.3.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.8.0.1" />
</ItemGroup>
```

in your `.csproj` file.

@Noobicle ok, I'll reopen the issue then.

**Comment by TobiasBuchholz** [comment] 2023-11-20 11:40
Hey @Noobicle, I was able to resolve your build error by updating the underlying `Xamarin.Firebase.Analytics` to the newest version. This is now released with `Pluging.Firebase.Analytics 2.0.2` or `Plugin.Firebase 2.0.8`. Let me know if you still encounter any problems ✌️

**Comment by cagriy** [comment] 2023-11-20 11:57
Hi @TobiasBuchholz , is the similar issue I mentioned above ok to be tracked on this issue ?

**Comment by cagriy** [comment] 2023-11-20 16:59
@TobiasBuchholz , thank you. This didn't help. Here is a sample project: https://github.com/cagriy/FirebaseTest

I basically created a fresh .NET MAUI 7 project and only added Plugin.Firebase nugget. No other coding. It builds fine for iOS but fails on Android giving the following error:

<img width="1053" alt="image" src="https://github.com/TobiasBuchholz/Plugin.Firebase/assets/1134069/0c53310a-5d7f-43d0-957c-e255db9c5da9">

**Comment by tranb3r** [comment] 2023-11-20 19:28
@cagriy 
As mentioned in the documentation, you probably need to add this packages:
```
<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
    <PackageReference Include="Xamarin.AndroidX.Core" Version="1.12.0.2" />
    <PackageReference Include="Xamarin.AndroidX.Collection" Version="1.3.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.3.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.8.0.1" />
</ItemGroup>
```

**Comment by TobiasBuchholz** [comment] 2023-11-20 20:07
Exactly, and don't forget to restore the packages after you've added them to the `.csproj` file, e.g. by running `dotnet restore`.

**Comment by cagriy** [comment] 2023-11-21 18:02
@tranb3r , @TobiasBuchholz thanks for your help, and sorry for taking your time for something obvious.

**Comment by vhugogarcia** [comment] 2023-11-21 19:30
Thanks friends for sharing how to solve this issue. I can confirm, I personally solved the issue on my .NET MAUI 8 projects by updating to the latest version of Plugin.Firebase.Analytics as mentioned by our friend @TobiasBuchholz, and applying the following **ItemGroup** on the .csproj file. 

```xml
<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
    <PackageReference Include="Xamarin.AndroidX.Core" Version="1.12.0.2" />
    <PackageReference Include="Xamarin.AndroidX.Collection" Version="1.3.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.3.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.8.0.1" />
</ItemGroup>
```

**Closed** 2024-06-05 16:20 UTC
